root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -gcflags 'all=-N -l' -o bin/maglev ./cmd/api"
  bin = "bin/maglev"
  full_bin = "make run-dev"

  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "bin", ".git"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  log = "air-build-errors.log"
  stop_on_error = true
  kill_delay = "500ms"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false
